placeholders:
  maxPrestigeReached: "&7Max rank reached"
  defaultPrestigeDisplayName: "&7None"
questComplete:
  sound: UI_TOAST_CHALLENGE_COMPLETE
  title:
    enabled: true
    title: "&2&oCongratulations!"
    subtitle: "&fYou have reached prestige %display_name%"
  messages:
    - ""
    - " &2&oCongratulations!"
    - " &oYou have reached prestige %display_name%"
    - ""