placeholders:
  maxPrestigeReached: "&7&lMax"
  noPrestige: "&7&lNothing"
questComplete:
  sound:
    enabled: true
    type: UI_TOAST_CHALLENGE_COMPLETE
  title:
    enabled: true
    text: "&2&oCongratulations!"
    subText: "&fYou have reached prestige %display_name%"
  messages:
    enabled: true
    texts:
      - ""
      - " &2&oCongratulations!"
      - " &oYou have reached prestige %display_name%"
      - ""